### ISSUE TITLE
Firebase Function error

### ISSUE THREAD

**Issue by JDmko** [angular/angularfire#2165]
Hi, I try SSR, I followed the documentation. Locally when running the _npm run serve: ssr_ script, it works perfectly. The problem only occurs with_firebase serve_. When I '' view page source '' only static content is displayed but content from database is no longer displayed. I tried firebase deploy including function. I have an error in the function log. 

> Error: Cannot find module 'firebase/app'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at webpackUniversalModuleDefinition (/srv/dist/Carsgram-webpack/server.js:3:28)
    at Object.<anonymous> (/srv/dist/Carsgram-webpack/server.js:10:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

This error is preceded by a message:

> Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions

the last message is:

> Function execution took 310 ms, finished with status: 'crash'

I need help identifying the problem.

**Comment by jamesdaniels** [comment]
A) you need to upgrade to a paid plan to make external requests, that's why you're getting the error B) we've revamped the ssr stuff this year, should be a lot easier. Outdated.
