### ISSUE TITLE
[AngularFirePerformance]: AngularFirePerformanceModule throws an errors on server side rendering server

### ISSUE THREAD

**Issue by ATiltedTree** [angular/angularfire#2218]
When importing the `AngularFirePerformanceModule` in the base app module, like shown in [this example](https://github.com/angular/angularfire2/blob/master/docs/performance/getting-started.md#automatic-page-load-tracing), it throws an error on the server side rendering server because it cannot find the `window` object.

### Version info

**Angular:**
v8.2.9

**Firebase:**
v6.3.40

**AngularFire:**
v5.2.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Node: 5.2.1

### How to reproduce these conditions

**Steps to set up and reproduce**

Create a default new angular app with angularfire.
Follow these steps provided by [this repo](https://github.com/angular/angularfire2/blob/master/docs/universal/getting-started.md).
Add the `AngularFirePerformanceModule` to the base app module.
Build and start the ssr server.

### Debug output

**Errors in the JavaScript console**

```
ERROR FirebaseError: Performance: Window is not available. (performance/no window).
    at Object.factoryMethod [as performance] (/mnt/Data/Projects/loo/node_modules/@firebase/performance/dist/index.cjs.js:1325:33)
    at FirebaseAppImpl._getService (/mnt/Data/Projects/loo/node_modules/@firebase/app/dist/index.node.cjs.js:185:66)
    at FirebaseAppImpl.firebaseAppImpl.<computed> [as performance] (/mnt/Data/Projects/loo/node_modules/@firebase/app/dist/index.node.cjs.js:441:35)
    at eval (webpack://app/./node_modules/@angular/fire/performance/performance.js?:93:180)
    at ZoneDelegate.invoke (webpack://app/./node_modules/zone.js/dist/zone-node.js?:390:26)
    at Zone.run (webpack://app/./node_modules/zone.js/dist/zone-node.js?:149:43)
    at NgZone.runOutsideAngular (webpack://app/./node_modules/@angular/core/fesm5/core.js?:26644:28)
    at MapSubscriber.eval [as project] (webpack://app/./node_modules/@angular/fire/performance/performance.js?:93:137)
    at MapSubscriber._next (webpack://app/./node_modules/rxjs/_esm5/internal/operators/map.js?:40:35)
    at MapSubscriber.Subscriber.next (webpack://app/./node_modules/rxjs/_esm5/internal/Subscriber.js?:63:18) {
  code: 'performance/no window',
  name: 'FirebaseError'
}
```

### Expected behavior

The `AngularFirePerformanceModule` ignores that the `window` object is missing because it's running on the ssr server.

### Actual behavior

The `AngularFirePerformanceModule` throws an errors because it cannot find the `window` object.

**Comment by guilhermehtk** [comment]
```
if (typeof window === 'undefined') {
  global['window'] = {}
}
```
have you ever put this script in `server.ts`?

**Comment by jamesdaniels** [comment]
No longer an issue in the latest versions.

**Comment by igoraugustynski** [comment]
Actually it's still an issue with `"@angular/fire": "^7.6.1"` and `"firebase": "^9.23.0"`.
