### ISSUE TITLE
Angular Fire Deploy Seems not working in Windows

### ISSUE THREAD

**Issue by yingdi1** [angular/angularfire#2226]
Should be pretty latest version.

I am following this guide: https://github.com/angular/angularfire/blob/master/docs/deploy/getting-started.md

and running `ng run [ANGULAR_PROJECT_NAME]:deploy`
But I got below error:

An unhandled exception occurred: ENOENT: no such file or directory, open '\C\development\...\.firebaserc'
See "C:\Users\yingd\AppData\Local\Temp\ng-SwOxK7\angular-errors.log" for further details.

Below is detail in the file.
```
[error] Error: ENOENT: no such file or directory, open '\C\development\...\.firebaserc'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.getFirebaseProjectName (C:\development\...\node_modules\@angular\fire\schematics\utils.js:52:41)
    at Object.<anonymous> (C:\development\...\node_modules\@angular\fire\schematics\deploy\builder.js:26:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\development\...\node_modules\@angular\fire\schematics\deploy\builder.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I think it should be C:\ instead of \C\ since I am using windows.

**Comment by yingdi1** [comment]
Seems to be related to https://github.com/angular/angularfire/pull/2221/commits/d352ceccb4134bd64b4f4e3002016674e79548cb

**Comment by yingdi1** [comment]
what is ANGULAR_PROJECT_NAME in  https://github.com/angular/angularfire/blob/master/docs/deploy/getting-started.md?

**Comment by yingdi1** [comment]
It gives all kinds of errors and never work.

**Comment by yingdi1** [comment]
firebase deploy works.

**Comment by yingdi1** [comment]
So in total , I think d352cec will fix this issue, but even that is fixed , I still faced different errors when running ng run [ANGULAR_PROJECT_NAME]:deploy , but `firebase deploy` actually works after running `ng build --watch`
