### ISSUE TITLE
Uncaught (in promise) TypeError: Object(...) is not a function on RXJS6

### ISSUE THREAD

**Issue by JochenDB** [angular/angularfire#2228]
I'm running into a similar issue as #1866, #1700 and others.
The difference is, I'm already on rxjs6. I also have rxjs-compat6.

Is there anything else I can try?

### Version info

**Angular**:5.0.3 
**Firebase**:7.2.1
**AngularFire**:5.2.1
**Ionic**:3.9.5
**Cordova**:9.0.0
**rxjs**:6.3.3
**rxjs-compat**:6.3.3
**typescript**:3.6.4

### Debug output

** Errors in the JavaScript console **

`Unhandled Promise rejection: Object(...) is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object(...) is not a function
    at handler (VM32 vendor.js:203787)
    at VM32 vendor.js:203934
    at t.invoke (VM31 polyfills.js:3)
    at r.run (VM31 polyfills.js:3)
    at VM31 polyfills.js:3
    at t.invokeTask (VM31 polyfills.js:3)
    at r.runTask (VM31 polyfills.js:3)
    at o (VM31 polyfills.js:3)
    at e.invokeTask [as invoke] (VM31 polyfills.js:3)
    at p (VM31 polyfills.js:2)
    at XMLHttpRequest.v (VM31 polyfills.js:2) TypeError: Object(...) is not a function
    at handler (http://localhost:8100/build/vendor.js:203787:118)
    at http://localhost:8100/build/vendor.js:203934:17
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)`

**Comment by mfouadegy** [comment]
same problem with me :(

**Comment by JochenDB** [comment]
Fixed by downgrading firebase again to 6.6.2 @mfouadegy

**Comment by mfouadegy** [comment]
downgraded and same problem :( @JochenDB

**Comment by gayu1712** [comment]
Try, downgrading @angular/fire to 5.2.0

**Comment by mfouadegy** [comment]
i'm using angularfire2 @gayu1712

**Comment by miyabiya** [comment]
same problem

**Comment by miyabiya** [comment]
in my case, updated @angular/fire to 5.3.0-rc.0 is solved

**Comment by joaoeudes7** [comment]
Thanks @miyabiya!
This angularfire is very confuse!

**Comment by jamesdaniels** [comment]
Closing as outdated.
