### ISSUE TITLE
angular/universal deploying Angular 9 SSR to fire base issue

### ISSUE THREAD

**Issue by khaled6mmd** [angular/angularfire#2364]
I tried A lot of solutions for angular 8 but did not work

and tried fire base documentations on GitHub but they were out of date

I used ` ng add @nguniversal/express-engine` to covert and `npm run build:ssr -and npm serve:ssr` work fine

this is the last thing I have tried

[Getting started with AngularFire and Universal][1]

it builds alright, the problem with is with `npm run serve:ssr`

I get this error

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\Khaled\Desktop\coupons\dist\coupons-webpack\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)     
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coupons@0.0.0 serve:ssr: `node dist/coupons-webpack/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coupons@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Khaled\AppData\Roaming\npm-cache\_logs\2020-03-28T08_16_49_865Z-debug.log
```

  [1]: https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md

**Comment by khaled6mmd** [comment]
fixed it by re-doing the steps
