### ISSUE TITLE
Pre-Rendering Not Working w/ Firebase 7.13.1 → ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mazlano27** [angular/angularfire#2388]
### Version info

**Angular: 9.1.0**

**Firebase: 7.13.x**

**AngularFire: 6.0.0**

### How to reproduce these conditions

• Repo found here → https://github.com/mazlano27/repro-app-2
• Run 'npm install' followed by 'npm run build:all'

### Debug output

`ReferenceError: window is not defined
    at eval (webpack:///./node_modules/@firebase/firestore/dist/index.esm.js?:15021:11)
    at Module../node_modules/@firebase/firestore/dist/index.esm.js (/Users/Azlan_Mac/Desktop/Dev/TEMPLATES/repro-app-master/dist/repro-app/prerender.js:155:1)
    at __webpack_require__ (/Users/Azlan_Mac/Desktop/Dev/TEMPLATES/repro-app-master/dist/repro-app/prerender.js:20:30)
    at Object.@firebase/firestore (webpack:///./dist/repro-app-server/main.js?:165662:18)
    at __webpack_require__ (webpack:///./dist/repro-app-server/main.js?:20:30)
    at Module../node_modules/@angular/fire/__ivy_ngcc__/fesm2015/angular-fire-firestore.js (webpack:///./dist/repro-app-server/main.js?:103354:77)
    at __webpack_require__ (webpack:///./dist/repro-app-server/main.js?:20:30)
    at Object../src/app/app.component.ts (webpack:///./dist/repro-app-server/main.js?:165118:21)
    at __webpack_require__ (webpack:///./dist/repro-app-server/main.js?:20:30)
    at Object../src/app/app.module.ts (webpack:///./dist/repro-app-server/main.js?:165227:25)
`

### Expected behavior

Should pre-render routes. When using Firebase v7.8.0 → It works as it should.

### Actual behavior

Does not pre-render routes and throws error with Firebase v7.13.x

**Comment by addsmoll** [comment]
Add in prerender.ts

// ssr DOM
const domino = require('domino');
const fs = require('fs');
const path = require('path');
// index from browser build!
const template = fs.readFileSync(path.join('.', 'dist/browser', 'index.html')).toString();
// for mock global window by domino
const win = domino.createWindow(template);
// from server build

// mock
global['window'] = win;
// not implemented property and functions
Object.defineProperty(win.document.body.style, 'transform', {
    value: () => {
        return {
            enumerable: true,
            configurable: true,
        };
    },
});
// mock documnet
global['document'] = win.document;

**Comment by jamesdaniels** [comment]
This should no longer be an issue with the newer versions of AF & Firebase.
