### ISSUE TITLE
AngularFirestoreDocument.Update doesn't fire promise catch on error

### ISSUE THREAD

**Issue by BorjaFTW** [angular/angularfire#2389]
**Angular:** 8.2.14

**Firebase:** 7.12.0

**AngularFire:** 5.4.2

**Ionic:** 5.0.5

**OS:** Win 10

### How to reproduce these conditions

**Steps to set up and reproduce**

```
import { Injectable } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private firestore: AngularFirestore) { }

  public updateUser(userData: any) {
    const id = 'sampleId';
    auxUserData = undefined; // Needed to trigger error
    this.firestore.collection<User>('users').doc(id).update(auxUserData)
.then(response => console.log(response)).catch(e => alert(e));
  }
}
```

**Sample data and security rules**

Just configure a Firestore database and create the users collection if it's needed.

### Debug output

**Errors in the JavaScript console**

```
FirebaseError: Function DocumentReference.update() called with invalid data. Data must be an object, but it was: undefined
    at new n (http://localhost:8100/vendor.js:103628:19)
    at t.il (http://localhost:8100/vendor.js:113986:16)
    at kr (http://localhost:8100/vendor.js:114222:68)
    at t.ol (http://localhost:8100/vendor.js:114040:9)
    at t.update (http://localhost:8100/vendor.js:117533:31)
    at AngularFirestoreDocument.update (http://localhost:8100/vendor.js:80097:25)
    at UserService.updateUser (http://localhost:8100/main.js:1211:56)
    at handler (http://localhost:8100/user-module.js:185:42)
    at http://localhost:8100/vendor.js:130216:24
```

### Expected behavior

Print error with alert.

### Actual behavior

Console error at console.

**Comment by Unkn0wn0x** [comment]
How about to use a try-catch block?

```
public updateUser(userData: any): Promise<void> {
    
    try {

        const id: string = 'sampleId';
        const auxUserData: any = undefined;

        await this.firestore
            .collection<User>('users')
            .doc(id)
            .update(auxUserData);

        // Processing succeed
        return;
        
    } catch (error) {

        // Process your error here
        myLogger(error);
        
    }

}
```

Hope it helps.

Cheers
Unkn0wn0x

**Comment by jamesdaniels** [comment]
Strikes me as a jS SDK bug, if it hasn't been addressed already.
