### ISSUE TITLE
Angularfire messaging infinite loop when selecting to block notifications

### ISSUE THREAD

**Issue by anzap** [angular/angularfire#2506]
### Version info

**Angular:**
8.0.x
**Firebase:**

**AngularFire:**
6.0.0
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Steps to set up and reproduce**

I have setup angularfire and firebase messaging for my app as described in the readme. When i enter the application i get the popup to allow or block notifications from the app.
If i select to allow everything works as it should.
If i select to block notifications i get the error below in the browser console which leads to an infinite loop causing the browser to freeze and crash.

### Debug output

** Errors in the JavaScript console **
```
FirebaseError: Messaging: The notification permission was not granted and blocked instead. (messaging/permission-blocked).
    at WindowController.<anonymous> (http://admin.localhost:4200/firebase-messaging.js:2541:49)
    at step (http://admin.localhost:4200/firebase-messaging.js:3356:23)
    at Object.next (http://admin.localhost:4200/firebase-messaging.js:3337:53)
    at fulfilled (http://admin.localhost:4200/firebase-messaging.js:3327:58)
    at ZoneDelegate.invoke (http://admin.localhost:4200/polyfills.js:5531:26)
    at Zone.run (http://admin.localhost:4200/polyfills.js:5296:43)
    at http://admin.localhost:4200/polyfills.js:6027:36
    at ZoneDelegate.invokeTask (http://admin.localhost:4200/polyfills.js:5563:31)
    at Zone.runTask (http://admin.localhost:4200/polyfills.js:5340:47)
    at drainMicroTaskQueue (http://admin.localhost:4200/polyfills.js:5731:35)
```

If i check the code in firebase-messaging.js in browser console this is the method being called infinitely.

```
WindowController.prototype.getToken = function () {
        return Object(tslib__WEBPACK_IMPORTED_MODULE_3__["__awaiter"])(this, void 0, void 0, function () {
            var swRegistration;
            return Object(tslib__WEBPACK_IMPORTED_MODULE_3__["__generator"])(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        if (!this.vapidKey) {
                            this.vapidKey = DEFAULT_VAPID_KEY;
                        }
                        return [4 /*yield*/, this.getServiceWorkerRegistration()];
                    case 1:
                        swRegistration = _a.sent();
                        if (!(Notification.permission === 'default')) return [3 /*break*/, 3];
                        // The user hasn't allowed or denied notifications yet. Ask them.
                        return [4 /*yield*/, Notification.requestPermission()];
                    case 2:
                        // The user hasn't allowed or denied notifications yet. Ask them.
                        _a.sent();
                        _a.label = 3;
                    case 3:
                        if (Notification.permission !== 'granted') {
                            throw ERROR_FACTORY.create("permission-blocked" /* PERMISSION_BLOCKED */);
                        }
                        return [2 /*return*/, getToken(this.firebaseDependencies, swRegistration, this.vapidKey)];
                }
            });
        });
    };
```
Anyone else facing the same issue?

**Comment by jamesdaniels** [comment]
I think this might be due to a recent Firebase JS SDK break, where getToken actually makes the permission request for you. I changed AngularFire's use of this API to try to act as documented. 

Can you try the latest canary and see if that helps? `6.0.3-canary.7cb6c03`

**Comment by jamesdaniels** [comment]
Seems to be working for me in `6.0.3` going to close. Please open another issue if still having issues.
