### ISSUE TITLE
ERROR TypeError: fire._firebaseAppFactory(...).firestore is not a function

### ISSUE THREAD

**Issue by harsh7510** [angular/angularfire#2524]
### Version info

**Angular: 9.1.11**

**Firebase:7.14.5**

**AngularFire:5.4.2**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**
 this error in my existing project.during SSR in angular 9.1.11
when I run npm run build:ssr its build successfully.
but when I try to run npm run serve:ssr and open http://localhost:4200 port in browser this error is accrued. 

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
<code>
TypeError: fire._firebaseAppFactory(...).firestore is not a function
    at F:\pro\prod\dist\prod\server\main.js:1:3023795
    at ZoneDelegate.invoke (F:\pro\prod\dist\prod\server\main.js:1:3300562)
    at Zone.run (F:\pro\prod\dist\prod\server\main.js:1:3292976)
    at NgZone.runOutsideAngular (F:\pro\prod\dist\prod\server\main.js:1:4153270)
    at new AngularFirestore (F:\pro\prod\dist\prod\server\main.js:1:3023696)
    at Object.AngularFirestore_Factory [as factory] (F:\pro\prod\dist\prod\server\main.js:1:3025643)
    at R3Injector.hydrate (F:\pro\prod\dist\prod\server\main.js:1:3913289)
    at R3Injector.get (F:\pro\prod\dist\prod\server\main.js:1:3909661)
    at injectInjectorOnly (F:\pro\prod\dist\prod\server\main.js:1:3775803)
    at Object.ɵɵinject (F:\pro\prod\dist\prod\server\main.js:1:3776010)
</code>
** Output from `firebase.database().enableLogging(true);` **
this error comes from here.
** Screenshots **

![image](https://user-images.githubusercontent.com/62533427/85712692-32e86800-b706-11ea-9a05-653d75b23770.png)

**Comment by jamesdaniels** [comment]
A work-around was added to 6.0, https://github.com/angular/angularfire/pull/2347/files#diff-0b0d34eeb968dfc88909429e8807bd73R123
