### ISSUE TITLE
Cannot connect to local firestore emulator: ERROR FirebaseError:  false for 'get' @ L14

### ISSUE THREAD

**Issue by jonathan-chin** [angular/angularfire#2564]
hi all, I'm trying to connect my client code to the locally running firestore emulator. I've implemented the fix from #2183 by using the provider in app.module.ts

```
providers: [
        [...]
        {
            provide: FIRESTORE_SETTINGS,
            useValue: environment.emulator ? {
                host: 'localhost:8080',
                ssl: false
            } : {}
        }
    ]
```

however, my client then throws a weird error:

```
ERROR FirebaseError: 
false for 'get' @ L14
    at new n (http://localhost:8100/vendor.js:116516:23)
    at t.ni (http://localhost:8100/vendor.js:119662:16)
    at t.pi (http://localhost:8100/vendor.js:119821:195)
    at n.onMessage (http://localhost:8100/vendor.js:126333:33)
    at http://localhost:8100/vendor.js:126286:26
    at http://localhost:8100/vendor.js:126317:37
    at http://localhost:8100/vendor.js:124224:31
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3470:30)
    at Zone.run (http://localhost:8100/polyfills.js:3229:47)
    at http://localhost:8100/polyfills.js:3963:40
```

the error seems to be generated when I actually try to interact with the firestore database from my client:

```
this.angularFirestore
  .collection('users')
  .doc(user.uid)
  .snapshotChanges()
  .subscribe((snapshot) => {
    // do stuff
  });
```

I am running the emulator suite no problem and have already successfully directed my function calls to it (which also writes to the firestore emulator, so I know that is working). any insights?

if I run the same exact client code without the provider (ie running it against the real firestore server), it works (except, of course, the data/contents on the real server doesn't match the ones on the emulated server).

### Version info

**Angular:** 9.1.6

**Firebase:** 7.15.0

**AngularFire:** 6.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Ionic 5.0.0

**Comment by jonathan-chin** [comment]
I've figured this out. when trying to a similar firestore call (`.get()` instead of `.snapshotChanges().subscribe()`), I get a very similar error but it adds `[code=permission-denied]'. it's still the same enigmatic `false for 'get' @ L14` otherwise.

this ultimately ended up being a firestore rules issue.
