### ISSUE TITLE
Error: Type AngularFirestore does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by ozeltser** [angular/angularfire#2669]
I am trying to use firebase in my angular 9 app.
I am following the guide here: https://dottedsquirrel.com/firebase/how-to-create-and-read-things-in-firebase/

I am getting the following error: 

```
Error: Type AngularFirestore does not have 'ɵmod' property.
    at getNgModuleDef (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:1839:1)
    at recurse (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:24878:1)
    at recurse (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:24889:1)
    at registerNgModuleType (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:24874:1)
    at new NgModuleFactory$1 (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:24988:1)
    at compileNgModuleFactory__POST_R3__ (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:28544:1)
    at PlatformRef.bootstrapModule (c:\Users\Oleg\source\repos\is-it-over-yet\node_modules\@angular\core\__ivy_ngcc__\fesm2015\core.js:28782:1)
    at Module.zUnb (c:\Users\Oleg\source\repos\is-it-over-yet\src\main.ts:12:26)
    at __webpack_require__ (http://localhost:4200/runtime.js:85:30)
    at Object.0 (http://localhost:4200/main.js:11:18)
```

My environment: 
```
ng --version
Angular CLI: 11.0.1
Node: 12.13.0
OS: win32 x64
```
My package.json has 
 `
"firebase": "^8.0.2",
`
And my app.module has
```
import { AngularFireModule } from '@angular/fire';
import { AngularFirestore } from '@angular/fire/firestore';
...
imports: [
....
    AngularFireModule.initializeApp(environment.firebaseConfig),
    AngularFirestore
],
  providers: [AngularFirestore],
```
Is it an angular 11 - related bug or I am missing something?

**Comment by jamesdaniels** [comment]
In your imports you want `AngularFirestoreModule` rather than `AngularFirestore`.
