### ISSUE TITLE
SSR - Unhandled Promise rejection: app.analytics is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: app.analytics is not a function

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#2698]
### Version info
<pre>
<code>
    "@angular/core": "^9.1.11",
    "@angular/fire": "^5.4.2",
    "@angular/platform-server": "^9.1.11",
    "@nguniversal/express-engine": "^9.1.1",
    "@angular/fire": "^5.4.2",
    "firebase": "^7.24.0",
    "express": "^4.15.2",
</code>
</pre>

### Debug output

** Errors in the JavaScript console **

<pre><code>
Unhandled Promise rejection: app.analytics is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: app.analytics is not a function
    at MapSubscriber.project (D:\Angular\konigs-art\dist\server\main.js:1:2071890)
    at MapSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:11580785)
    at MapSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at MapSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:11580891)
    at MapSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at SwitchMapSubscriber.notifyNext (D:\Angular\konigs-art\dist\server\main.js:1:9659624)
    at InnerSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:2336593)
    at InnerSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at D:\Angular\konigs-art\dist\server\main.js:1:9282330
    at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513) TypeError: app.analytics is not a function
    at MapSubscriber.project (D:\Angular\konigs-art\dist\server\main.js:1:2071890)
    at MapSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:11580785)
    at MapSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at MapSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:11580891)
    at MapSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at SwitchMapSubscriber.notifyNext (D:\Angular\konigs-art\dist\server\main.js:1:9659624)
    at InnerSubscriber._next (D:\Angular\konigs-art\dist\server\main.js:1:2336593)
    at InnerSubscriber.next (D:\Angular\konigs-art\dist\server\main.js:1:2709605)
    at D:\Angular\konigs-art\dist\server\main.js:1:9282330
    at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
ERROR Error: Uncaught (in promise): TypeError: Object(...)(...).firestore is not a function
TypeError: Object(...)(...).firestore is not a function
    at D:\Angular\konigs-art\dist\server\main.js:1:5715257
    at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
    at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:9511927)
    at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:10182673)
    at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:5715138)
    at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:5716733)
    at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:9955693)
    at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:9952423)
    at injectInjectorOnly (D:\Angular\konigs-art\dist\server\main.js:1:9837493)
    at Module.ɵɵinject (D:\Angular\konigs-art\dist\server\main.js:1:9837659)
    at resolvePromise (D:\Angular\konigs-art\dist\server\main.js:1:9529341)
    at resolvePromise (D:\Angular\konigs-art\dist\server\main.js:1:9528318)
    at D:\Angular\konigs-art\dist\server\main.js:1:9531145
    at ZoneDelegate.invokeTask (D:\Angular\konigs-art\dist\server\main.js:1:9520445)
    at Object.onInvokeTask (D:\Angular\konigs-art\dist\server\main.js:1:10181121)
    at ZoneDelegate.invokeTask (D:\Angular\konigs-art\dist\server\main.js:1:9520335)
    at Zone.runTask (D:\Angular\konigs-art\dist\server\main.js:1:9513010)
    at drainMicroTaskQueue (D:\Angular\konigs-art\dist\server\main.js:1:9524053)
    at ZoneTask.invokeTask (D:\Angular\konigs-art\dist\server\main.js:1:9522094)
    at Server.ZoneTask.options.useG.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9521859) {
  rejection: TypeError: Object(...)(...).firestore is not a function
      at D:\Angular\konigs-art\dist\server\main.js:1:5715257
      at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
      at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:9511927)
      at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:10182673)
      at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:5715138)
      at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:5716733)
      at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:9955693)
      at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:9952423)
      at injectInjectorOnly (D:\Angular\konigs-art\dist\server\main.js:1:9837493)
      at Module.ɵɵinject (D:\Angular\konigs-art\dist\server\main.js:1:9837659),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: Object(...)(...).firestore is not a function
        at D:\Angular\konigs-art\dist\server\main.js:1:5715257
        at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
        at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:9511927)
        at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:10182673)
        at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:5715138)
        at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:5716733)
        at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:9955693)
        at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:9952423)
        at injectInjectorOnly (D:\Angular\konigs-art\dist\server\main.js:1:9837493)
        at Module.ɵɵinject (D:\Angular\konigs-art\dist\server\main.js:1:9837659)
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: <ref *2> ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: Object(...)(...).firestore is not a function
          at D:\Angular\konigs-art\dist\server\main.js:1:5715257
          at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
          at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:9511927)
          at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:10182673)
          at new AngularFirestore (D:\Angular\konigs-art\dist\server\main.js:1:5715138)
          at Object.AngularFirestore_Factory [as factory] (D:\Angular\konigs-art\dist\server\main.js:1:5716733)
          at R3Injector.hydrate (D:\Angular\konigs-art\dist\server\main.js:1:9955693)
          at R3Injector.get (D:\Angular\konigs-art\dist\server\main.js:1:9952423)
          at injectInjectorOnly (D:\Angular\konigs-art\dist\server\main.js:1:9837493)
          at Module.ɵɵinject (D:\Angular\konigs-art\dist\server\main.js:1:9837659)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)]
  }
}
</code></pre>

### angular.json - server build
.. config
<pre>
<code>
            "externalDependencies": [
              "@firebase/firestore",
              "@firebase/analytics"
            ]
</code>
</pre>

**Comment by Karman40** [comment]
Thanks, it is work after update.
I dont line new auth code 👎 much more complicated than in v5

**Comment by sanjayp1111** [comment]
Still having same issue in angular with updated version

**Comment by sanjayp1111** [comment]
Kindly reply on these
