### ISSUE TITLE
SSR - ERROR FirebaseError: Performance: Window is not available. (performance/no window).

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#2699]
### Version info
<pre>
<code>
    "@angular/core": "^9.1.11",
    "@angular/fire": "^5.4.2",
    "@angular/platform-server": "^9.1.11",
    "@nguniversal/express-engine": "^9.1.1",
    "@angular/fire": "^5.4.2",
    "firebase": "^7.24.0",
    "express": "^4.15.2",
</code>
</pre>

### Debug output

** Errors in the JavaScript console **

<pre><code>
ERROR FirebaseError: Performance: Window is not available. (performance/no window).
    at factoryMethod (D:\Angular\konigs-art\dist\server\vendors~firebase-performance.js:1:44737)
    at Component.instanceFactory (D:\Angular\konigs-art\dist\server\vendors~firebase-performance.js:1:45194)
    at Provider.getOrInitializeService (D:\Angular\konigs-art\dist\server\main.js:1:5709407)
    at Provider.getImmediate (D:\Angular\konigs-art\dist\server\main.js:1:5707270)
    at FirebaseAppImpl._getService (D:\Angular\konigs-art\dist\server\main.js:1:9690956)
    at FirebaseAppImpl.firebaseAppImpl.<computed> [as performance] (D:\Angular\konigs-art\dist\server\main.js:1:9694885)
    at D:\Angular\konigs-art\dist\server\main.js:1:12425941
    at ZoneDelegate.invoke (D:\Angular\konigs-art\dist\server\main.js:1:9519513)
    at Zone.run (D:\Angular\konigs-art\dist\server\main.js:1:9511927)
    at NgZone.runOutsideAngular (D:\Angular\konigs-art\dist\server\main.js:1:10182673) {
  code: 'performance/no window'
}
</code></pre>

### angular.json - server build
.. config
<pre>
<code>
            "externalDependencies": [
              "@firebase/firestore",
              "@firebase/analytics"
            ]
</code>
</pre>

![image](https://user-images.githubusercontent.com/32225709/100521910-27aed200-31a7-11eb-9648-fe79e83ad8d9.png)

**Comment by jamesdaniels** [comment]
No longer an issue with the current versions of Firebase & AngularFire.

**Comment by Karman40** [comment]
Thanks, it is work after update.
I dont line new auth code 👎 much more complicated than in v5

**Comment by jamesdaniels** [comment]
Shaves a lot of KB off your main bundle though! 😉

**Comment by Karman40** [comment]
Yes, that's great 💯🥇. Maybe if I used to do that I would say how good it is, the transition is difficult :-)

**Comment by igoraugustynski** [comment]
Actually it's still an issue with `"@angular/fire": "^7.6.1"` and `"firebase": "^9.23.0"`.
