### ISSUE TITLE
Can't display content of a collection locally - FirebaseError: Missing or insufficient permissions

### ISSUE THREAD

**Issue by SimonChatillon** [angular/angularfire#2751]
Hello, I have followed everything explained in the [Quickstart](https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md), but I still can't display the content of my firebase collection locally. I am getting the following error : 
`ERROR FirebaseError: Missing or insufficient permissions.`

My fire store is in test mode with the following ruleset : 
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```
I tried a lot of things but can't manage to solve this, anyone alse has encountered this issue ?

### Version info

**Angular:** 11.1.1

**Firebase:** 8.2.5

**AngularFire:** 6.1.4

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

Just create a new firebase app, a new cloud firestore in test mode, follow the angularfire quickstart guide and try to display the content of a collection in your app

### Debug output

** ERROR FirebaseError: Missing or insufficient permissions.
    at new e (http://localhost:4200/vendor.js:2360:23)
    at http://localhost:4200/vendor.js:12963:28
    at http://localhost:4200/vendor.js:12964:18
    at e.onMessage (http://localhost:4200/vendor.js:12986:10)
    at http://localhost:4200/vendor.js:12903:26
    at http://localhost:4200/vendor.js:12934:37
    at http://localhost:4200/vendor.js:17892:31
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:462:26)
    at Zone.run (http://localhost:4200/polyfills.js:224:43)
    at http://localhost:4200/polyfills.js:1366:36 **

**Comment by SimonChatillon** [comment]
I finally figured out why this wasn't working. I forgot I was using an authorization request header with ModHeader chrome extension for my work from home, and it was probably blocking the firestore requests...
Issue closed.
