### ISSUE TITLE
Ubuntu 20.04.2 LTS doesn't work with https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md

### ISSUE THREAD

**Issue by yingdi1** [angular/angularfire#3192]
```
di@di:~/development/firebase$ cd second-angularfire/
di@di:~/development/firebase/second-angularfire$ ng add @angular/fire
? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see https://angular.io/analytics. No
ℹ Using package manager: npm
✔ Found compatible package version: @angular/fire@7.3.0.
✔ Package information loaded.

The package @angular/fire@7.3.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
UPDATE package.json (1111 bytes)
✔ Packages installed successfully.
? What features would you like to setup? ng deploy -- hosting, Authentication, Firestore, Realtime Database, Analytics, Cloud Functions (callable), Cloud Messaging, Performance Monitoring, Cloud Storage,
 Remote Config
✖ Package install failed.
/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read property 'message' of undefined
    at Object.error (/home/di/development/firebase/second-angularfire/node_modules/@angular/cli/models/schematic-command.js:436:47)
    at SafeSubscriber.__tryOrUnsub (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at TapSubscriber._error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/tap.js:75:26)
    at TapSubscriber.Subscriber.error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.SimpleOuterSubscriber.notifyError (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:72:26)
    at SimpleInnerSubscriber._error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:30:21)
    at SimpleInnerSubscriber.Subscriber.error (/home/di/development/firebase/second-angularfire/node_modules/@angular-devkit/schem
![Screenshot from 2022-03-27 22-12-23](https://user-images.githubusercontent.com/37271055/160325418-582451c1-36a7-451b-8867-34c624b65d04.png)
atics/node_modules/rxjs/internal/Subscriber.js:72:18)
```

Steps to reproduce:

```
npm install -g @angular/cli
ng new second-angularfire
cd second-angularfire/
ng add @angular/fire
```
I run this on March 27th. So latest Angular/firebase combination.

Below is my Ubuntu version.
Windows seems to be working fun, Just in linux I got the error. Cannot wait to see it fixed.

```
di@di:~/development/firebase/second-angularfire$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by yingdi1** [comment]
Actually, this is not an issue. I haven't run `firebase login` yet. Anyway, that is why it failed. I would appreciate it if the error message can remind use to login instead of saying this.
