### ISSUE TITLE
Package install fails with `TypeError: Cannot read properties of undefined (reading 'message')`

### ISSUE THREAD

**Issue by digitalex** [angular/angularfire#3199]
### Version info

**Angular:** 13.3.0

**Firebase:** 10.5.0

**AngularFire:** 7.3.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Mac OS 12.3, M1 (Apple Silicon)

### How to reproduce these conditions

1. Install Angular 13.3.0 and Firebase 10.5.0.
2. Set up firebase (login).
3. Attempt install of AngularFire with `ng add @angular/fire`. Check hosting and Firestore.

### Debug output

```
my-machine:project me$ ng add @angular/fire
Skipping installation: Package already installed
UPDATE package.json (1142 bytes)
✔ Packages installed successfully.
? What features would you like to setup? ng deploy -- hosting, Firestore
✖ Package install failed.
/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read properties of undefined (reading 'message')
    at Object.error (/Users/<redacted>/node_modules/@angular/cli/models/schematic-command.js:436:47)
    at SafeSubscriber.__tryOrUnsub (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at TapSubscriber._error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/tap.js:75:26)
    at TapSubscriber.Subscriber.error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.SimpleOuterSubscriber.notifyError (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:72:26)
    at SimpleInnerSubscriber._error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:30:21)
    at SimpleInnerSubscriber.Subscriber.error (/Users/<redacted>/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:72:18)
```

**Comment by digitalex** [comment]
Duplicate of #3105
