### ISSUE TITLE
ng add @angular/fire throws error

### ISSUE THREAD

**Issue by ac-f** [angular/angularfire#3278]
### My Env
Angular CLI: 14.2.1
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: darwin arm64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@angular/fire                   7.4.1
@schematics/angular             14.2.1
rxjs                            7.5.6
typescript                      4.7.4

### Version info

**Angular: 14.2.0**

**Firebase: 9.12.1**

**AngularFire: 7.4.1**

### How to reproduce these conditions

1. Create a brand new ng project by ng-cli
2. `ng add @angular/fire` or `ng add @angular/fire@latest`
3. After I choose what tool I needed, it comes an error

> ✖ Package install failed.
An unhandled exception occurred: catch clause variable is not an Error instance
See "/private/var/folders/3k/75w_2fh90md9p77mx769qfmr0000gn/T/ng-rSgpUq/angular-errors.log" for further details.

4. open the log file

> [error] AssertionError [ERR_ASSERTION]: catch clause variable is not an Error instance
    at assertIsError (/Users/xxx/newproject/node_modules/@angular/cli/src/utilities/error.js:19:26)
    at AddCommandModule.runSchematic (/Users/xxx/newproject/node_modules/@angular/cli/src/command-builder/schematics-command-module.js:311:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AddCommandModule.executeSchematic (/Users/xxx/newproject/node_modules/@angular/cli/src/commands/add/cli.js:283:20)
    at async AddCommandModule.handler (/Users/xxx/newproject/node_modules/@angular/cli/src/command-builder/command-module.js:109:24)

**Comment by johnmckay-reward** [comment]
@ac-f Did you figure this out? I'm getting the same.

**Comment by ac-f** [comment]
Hey @johnmckay-reward  , 
My solution is add `sudo`  in the command, like `sudo ng add @angular/fire@latest`.
I think there's something wrong when I setted up my env.
