### ISSUE TITLE
getToken error

### ISSUE THREAD

**Issue by Jorsary** [angular/angularfire#3295]
I just followed the instructions here 
https://firebase.google.com/docs/cloud-messaging/js/receive?authuser=0&hl=en#web-version-9
i get this error when using getToken
`
FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: Request contains an invalid argument." (installations/request-failed).
    at getErrorFromResponse (common.ts:53:1)
    at async createInstallationRequest (create-installation-request.ts:77:1)
    at async registerInstallation (get-installation-entry.ts:138:1)
    at async completeInstallationRegistration (get-token.ts:51:1)
    at async getToken (get-token.ts:36:1)
    at async getHeaders (requests.ts:157:1)
    at async requestGetToken (requests.ts:43:1)
    at async getNewToken (token-manager.ts:139:1)
    at async requestPermission (App.tsx:93:1)
`

**Comment by Jorsary** [comment]
close
