### ISSUE TITLE
AssertionError when trying to add @angular/fire via "ng add"

### ISSUE THREAD

**Issue by Deval99** [angular/angularfire#3330]
### Version info

**Angular: 15.2.5 (@angular/cli version : 15.2.4 (latest))**

**Firebase: 9.19.1**

**AngularFire: 7.5.0**

**OS : Ubuntu 22.04.2 LTS**

### How to reproduce these conditions

$ ng new
    - add angular routing
    - use scss
$ cd myProject
$ npm i firebase
$ ng add @angular/fire 
    - it will add @angular/fire 7.5.0
    - when asked which packages you want, i had selected "ng deploy -- hosting" (i.e. default one only)
    - when selecting other than "ng deploy -- hosting", same error.

### Problem 

✖ Package install failed.
An unhandled exception occurred: catch clause variable is not an Error instance
See "/tmp/ng-nsorVM/angular-errors.log" for further details.

### /tmp/ng-nsorVM/angular-errors.log : 

[error] AssertionError [ERR_ASSERTION]: catch clause variable is not an Error instance
    at assertIsError (<PROJECT_PATH>/node_modules/@angular/cli/src/utilities/error.js:19:26)
    at AddCommandModule.runSchematic (<PROJECT_PATH>/node_modules/@angular/cli/src/command-builder/schematics-command-module.js:295:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCommandModule.executeSchematic (<PROJECT_PATH>/node_modules/@angular/cli/src/commands/add/cli.js:285:20)
    at async AddCommandModule.handler (<PROJECT_PATH>/node_modules/@angular/cli/src/command-builder/command-module.js:118:24)

### Expected behavior

ng add should add angular/fire to the project

### Actual behavior

gives error as mentioned above

### What have i tried

1) Degrading angular version to 15.0.0 and 14.0.0 (while maintaining [compatibility matrix](https://github.com/angular/angularfire#compatibility), and also changed global version)

**Comment by jamesdaniels** [comment]
This should be addressed in 7.6.0, which is being cut now
