### ISSUE TITLE
Sessions are not persisted (accross tabs?) and setPersistence() throwing error

### ISSUE THREAD

**Issue by falk-stefan** [angular/angularfire#3340]
### Versions

```none
Angular:        15
@angular/fire:  7.5.0
```

### Description

Logging in a user inside my Angular app is working. 

I am able to refresh the page and the user remains logged in.

However, opening a new tab and re-visiting the website reveals that the user-token and their credentials couldn't be loaded. 

Afaik it shouln't be necessary to `setPersistence()` but if I'm trying 

```typescript
public auth: Auth = inject(Auth);

constructor() {
  this.auth.setPersistence({type: "LOCAL"}).then();
}
```

I'm getting the following error:

```none
ERROR Error: Uncaught (in promise): Error: INTERNAL ASSERTION FAILED: Expected a class definition
Error: INTERNAL ASSERTION FAILED: Expected a class definition
    at debugFail (index-3363a72a.js:497:11)
    at debugAssert (index-3363a72a.js:508:9)
    at _getInstance (index-3363a72a.js:530:5)
    at index-3363a72a.js:2461:59
```

Using the following imports

```typescript
import {
  Auth,
  getRedirectResult,
  GoogleAuthProvider,
  idToken,
  signInWithPopup,
  signInWithRedirect,
  user,
  User
} from "@angular/fire/auth";
```

**Comment by falk-stefan** [comment]
I'm sorry, this was a mistake on my end. :man_facepalming:
