### ISSUE TITLE
AngularFireModule is asked while Unit testing

### ISSUE THREAD

**Issue by sivanshkamat** [angular/angularfire#3380]
I am trying to unit test my angular project where I added firebase for authentication and realtime database.
The project runs with no error but while unit testing: i get following error:
Error: Either AngularFireModule has not been provided in your AppModule (this can be done manually or implictly using
provideFirebaseApp) or you're calling an AngularFire method outside of an NgModule (which is not supported).
    at getSchedulers (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/fire/fesm2015/angular-fire.js:154:15)
    at runOutsideAngular (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/fire/fesm2015/angular-fire.js:160:12)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/fire/fesm2015/angular-fire.js:227:21
    at new AuthService (http://localhost:9876/_karma_webpack_/webpack:/src/app/services/auth.service.ts:15:27)
    at Object.factory (ng:///AuthService/ɵfac.js:4:10)
    at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:9276:35)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:9164:33)
    at TestBedImpl.inject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:26246:52)
    at Function.TestBed [as inject] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/testing.mjs:26105:37)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/servic
    
    
    
   Here, I have created a Authentication service for required signup, login and logout functions:
   
   import { Injectable } from '@angular/core';
import {  from, Observable,} from 'rxjs';
import {
  Auth,
  signInWithEmailAndPassword,
  authState,
  createUserWithEmailAndPassword,
  UserCredential,
} from '@angular/fire/auth';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  currentUser$ = authState(this.auth);

  signUp(email: string, password: string): Observable<UserCredential> {
    return from(createUserWithEmailAndPassword(this.auth, email, password));
  }

  login(email: any, password: any): Observable<any> {
    return from(signInWithEmailAndPassword(this.auth, email, password));
  }
  
  logout(): Observable<any> {
    return from(this.auth.signOut());
  }  constructor(public auth: Auth) {}

}

Please keep me posted.

**Comment by davideast** [comment]
Duplicate #3383
