### ISSUE TITLE
AngularfirePerformance in main.ts

### ISSUE THREAD

**Issue by sanderschnydrig** [angular/angularfire#3420]
I tried to find information about this but couldn't find anything. Is it possible to use AngularfirePerformance to monitor the Angular bootstrapping in main.ts?

Using this code and @angular/fire at version ^7.6.1:
```typescript
import { AngularFirePerformance } from '@angular/fire/compat/performance';
const performance = inject(AngularFirePerformance)
```

I'm getting this error:
```console
core.mjs:4768 Uncaught Error: NG0203: inject() must be called from an injection context
    at injectInjectorOnly (core.mjs:4768:1)
    at ɵɵinject (core.mjs:4778:1)
    at 14431 (main.ts:25:27)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (|groupOptions: {}|namespace object:239:1)
    at |groupOptions: {}|namespace object:239:1
    at __webpack_require__.O (chunk loaded:23:1)
    at |groupOptions: {}|namespace object:239:1
    at webpackJsonpCallback (jsonp chunk loading:71:1)
    at main.js:1:59
```

**Comment by armando-navarro** [comment]
The NG0203 error here is Angular's injection-context rule: `inject()` can only run inside a constructor, a factory, or an explicit injection context, so calling it at the top level of `main.ts` will always throw, independent of AngularFire.

This was on the compat performance API in the 7.6.1 era. I'm closing this as a usage issue, but if you hit an injection-context error from within a proper Angular context on a current version, please open a new issue with a minimal reproduction.
