### ISSUE TITLE
Angular 16.2.0 - Set Firestore active - Error

### ISSUE THREAD

**Issue by mwaldheim** [angular/angularfire#3426]
### Version info

**Angular:** 16.2.0

**Firebase:** 9.23.0

**AngularFire:** 7.6.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Node 20.5.1; Windows 11; Google Chrome (Lates)

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

none

**Steps to set up and reproduce**

Install an Angular Client with version 16.2.0 and add "ng add @angular/fire" (for Module and Standalone the same Error.

Add the Firebase Config. Then add Firestore and compiling crashed...

Angular is setup in Standalone. I add this to app.config.ts, what ist included to main.ts (boostrapApplication(_, appConfig).

```ts

import { firebaseConfig } from './app.firebase';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { getStorage, provideStorage } from '@angular/fire/storage';
import { getAuth, provideAuth } from '@angular/fire/auth';
import { getFirestore, provideFirestore } from '@angular/fire/firestore';

export const appConfig: ApplicationConfig = {
  providers: [
     ...
    importProvidersFrom(provideFirebaseApp(() => initializeApp(firebaseConfig))),
    importProvidersFrom(provideStorage(() => getStorage())),
    importProvidersFrom(provideFirestore(() => getFirestore())), // Error comes only when set this
    importProvidersFrom(provideAuth(() => getAuth())),
  ],
};
```

Same Problem with ngModule....

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

```
node_modules/.pnpm/rxfire@6.0.4_firebase@9.23.0_rxjs@7.8.0/node_modules/rxfire/firestore/lite/interfaces.d.ts:8:29 - error TS2314: Generic type 'AggregateQuerySnapshot<T>' requires 1 type argument(s).

 8 export type CountSnapshot = lite.AggregateQuerySnapshot<{
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9     count: lite.AggregateField<number>;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 }, any, DocumentData>;
```

** Screenshots **
![image](https://github.com/angular/angularfire/assets/31657644/14be27ae-a224-4f3e-a949-d2777c6bae47)

**Comment by Celtian** [comment]
Angular 16.2 is working with this 3 deps right now:

```
"@angular/fire": "7.2.0",
"firebase": "^10.3.1",
"rxfire": "^6.0.5",
```

**Comment by mwaldheim** [comment]
Sorry, but i can't aprove this. How does it work for Angular 16.2 Standalone?

![image](https://github.com/angular/angularfire/assets/31657644/735205d4-989a-4d14-8990-160cd0b3da99)

**Comment by sycohuesca** [comment]
rxfire@6.0.5 with error, solution:
npm i rxfire@6.0.0 or yarn add rxfire@6.0.0

**Comment by mwaldheim** [comment]
Your answer fix the first problem, but it gives me another Error:

![image](https://github.com/angular/angularfire/assets/31657644/9d9f764c-f655-4eb8-aa1f-5869f00259b1)

**Comment by CezaryStasiak** [comment]
Got same problem, out of the blue CI started failing with that error without any firebase related code changes or versions changes. Libs:
"@angular/core": "^14.2.12",
"@angular/fire": "^7.5.0",

**Comment by spock123** [comment]
Also suddenly getting this error, no code changes whatsoever:

```
NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:731:15)
    at ɵɵinject (core.mjs:744:42)
    at Object.FirebaseAppModule_Factory [as useFactory] (angular-fire-app.js:57:42)
```

NG 16.2.3

The issue comes as soon as I load the firestore, as mentioned above.

**Comment by mwaldheim** [comment]
I have now gone down to Angular 16.2.3. Unfortunately, this triggers a new problem. To be honest, I'm getting desperate. It is no longer possible to use Firebase properly with Angular.

```cmd
./node_modules/.pnpm/rxfire@6.0.1_firebase@9.23.0_rxjs@7.8.0/node_modules/rxfire/firestore/index.esm.js:304:25-38 - Error: export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib' (po
ssible exports: __assign, __asyncDelegator, __asyncGenerator, __asyncValues, __await, __awaiter, __classPrivateFieldGet, __classPrivateFieldSet, __createBinding, __decorate, __exportStar, __extends, __generator, __importDefault, __importStar, __makeTemplateObject, __metadata, __param, __read, __rest, __spread, __spreadArrays, __values)
```

**Comment by spock123** [comment]
> I have now gone down to Angular 16.2.3. Unfortunately, this triggers a new problem. To be honest, I'm getting desperate. It is no longer possible to use Firebase properly with Angular.
> 
> ```batchfile
> ./node_modules/.pnpm/rxfire@6.0.1_firebase@9.23.0_rxjs@7.8.0/node_modules/rxfire/firestore/index.esm.js:304:25-38 - Error: export '__spreadArray' (imported as '__spreadArray') was not found in 'tslib' (po
> ssible exports: __assign, __asyncDelegator, __asyncGenerator, __asyncValues, __await, __awaiter, __classPrivateFieldGet, __classPrivateFieldSet, __createBinding, __decorate, __exportStar, __extends, __generator, __importDefault, __importStar, __makeTemplateObject, __metadata, __param, __read, __rest, __spread, __spreadArrays, __values)
> ```

I also use pnpm and for me it was a version mismatch issue cause by pnpm.

Would it be possible for you to test your code with npm? Because if it works with npm, you just need to clear and reinstall all pnpm modules again

**Comment by rgant** [comment]
See: https://github.com/FirebaseExtended/rxfire/issues/88#issuecomment-1715851191

**Comment by mwaldheim** [comment]
Thank you, npm solves the problem. But still, it seems to be an error then when pnpm has problems with it.

The development team should definitely look at the case, as pnpm is becoming more and more useful. I can live with it temporarily.

**Comment by rgant** [comment]
I don't think it is an npm vs pnpm issue.

The core issue is that rxfire@6.0.4 introduced a breaking dependency change requiring firebase@10 instead of allowing both v9 & v10 as rxfire@6.0.3 does.

This is a violation of the standard semver protocol for version numbering. In my opinion rxfire@6.0.4 should have been rxfire@6.1.0. Which would have avoided these changes.

I don't use pnpm, but presumably by following my example `overrides` and their [documentation](https://pnpm.io/package_json#pnpmoverrides) you can produce a version for yourself that does the same thing.
