### ISSUE TITLE
JEST test problem @firebase/firestore: Firestore (9.23.0): FIRESTORE (9.23.0) INTERNAL ASSERTION FAILED: Unexpected state

### ISSUE THREAD

**Issue by fkolar** [angular/angularfire#3448]
### Version info

**Angular:**
v16 + jest

**Firebase:**
v9.23
**AngularFire:**
7.6

> I have tested all the combination supported 7.6.1 + firebase v9

### How to reproduce these conditions

Here is the repo that shows 

https://github.com/fkolar/firebase-test

**Steps to set up and reproduce**

see the README

### Debug output

** Errors in the JavaScript console **

```
 @firebase/firestore: Firestore (9.23.0): FIRESTORE (9.23.0) INTERNAL ASSERTION FAILED: Unexpected state

      at Logger.defaultLogHandler [as _logHandler] (node_modules/@firebase/logger/src/logger.ts:115:57)
      at Logger.Object.<anonymous>.Logger.error (node_modules/@firebase/logger/src/logger.ts:210:5)
      at logError (node_modules/@firebase/firestore/src/util/log.ts:59:15)
      at fail (node_modules/@firebase/firestore/src/util/assert.ts:35:3)
      at hardAssert (node_modules/@firebase/firestore/src/util/assert.ts:54:5)
      at fromBytes (node_modules/@firebase/firestore/src/remote/serializer.ts:264:5)
      at fromWatchChange (node_modules/@firebase/firestore/src/remote/serializer.ts:502:25)
      at PersistentListenStream.onMessage (node_modules/@firebase/firestore/src/remote/persistent_stream.ts:642:25)
      at node_modules/@firebase/firestore/src/remote/persistent_stream.ts:517:21

```

I have migrated to latest Angular with NX + JEST as Karma is less or not really supported by NX anymore. I have hard to run the tests. With these wierd problems. I see many references on the web but I am unable to apply the workarounds or anything onto this repo.

**Comment by armando-navarro** [comment]
Thanks for the report. The 'INTERNAL ASSERTION FAILED: Unexpected state' in your stack trace originates entirely inside firebase-js-sdk's Firestore serializer under Jest/jsdom, not in AngularFire, and it is a known problem with how the SDK resolves its module builds in that test environment.

Since it is not an AngularFire defect I'm closing this; the firebase-js-sdk tracker is the right place for it: https://github.com/firebase/firebase-js-sdk/issues. If you can reproduce a specifically AngularFire problem on the current release line, please open a fresh issue.
