### ISSUE TITLE
AngularFire 17.0.0 throwing errors with Angular 17.0.0

### ISSUE THREAD

**Issue by ecancil** [angular/angularfire#3493]
I have recently upgraded to the newest angularfire 17.0.0 and am having trouble getting some fairly straight forward things working.  Filled out the template below.  Thanks for your help.

### Version info

**Angular:** 17.0.0

**Firebase:** 10.7.1

**AngularFire:** 17.0.0

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

`Internal server error: R3InjectorError(Standalone[_AppComponent])[_ShareableService -> _ShareableService -> Firestore2 -> Firestore2]: 
  NullInjectorError: No provider for Firestore2!
      at NullInjector.get (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:5467:21) 
      at R3Injector.get (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:5918:27)   
      at R3Injector.get (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:5918:27)   
      at injectInjectorOnly (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:910:36)
      at Module.ɵɵinject (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:916:40)   
      at Object.ShareableService_Factory (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/src/app/shareable.service.ts:7:30)     
      at eval (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:6030:33)
      at runInInjectorProfilerContext (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:871:5)
      at R3Injector.hydrate (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:6029:9)
      at R3Injector.get (c:/Users/ecanc/OneDrive/Documents/CaloKiwi/public/card/node_modules/@angular/core/fesm2022/core.mjs:5909:23) (x2)
`

** Screenshots **

![Error]("https://snipboard.io/wKpF23.jpg")
![Injection]("https://snipboard.io/dHOni7.jpg")

### Expected behavior

Compiling and injecting correctly

### Actual behavior

Getting error when injecting

**Comment by aprilrjwilliams** [comment]
Having the same issue - did you find a solution?

**Comment by aprilrjwilliams** [comment]
@ecancil

**Comment by armando-navarro** [comment]
Thanks for the report.

`Firestore2` here is just the name the bundler gives AngularFire's modular `Firestore` DI token, so the error means the Firestore provider is not registered in the injector that is resolving it, rather than a bug in `@angular/fire`.

On a standalone app (which is the default from Angular 17) the providers must be in the bootstrap providers array, not in an `NgModule`:

```ts
// main.ts / app.config.ts
providers: [
  provideFirebaseApp(() => initializeApp(environment.firebase)),
  provideFirestore(() => getFirestore()),
]
```

The common trap during a v16 to v17 migration is that these were left in an `app.module.ts` that the standalone bootstrap (`bootstrapApplication`) no longer imports, so a `providedIn: 'root'` service resolving `Firestore` never sees them.

Could you share your `main.ts` and `app.config.ts`? That will confirm whether the providers are reaching the root injector. If they are present and it still fails, there is more going on and I will dig in.
