### ISSUE TITLE
reauthenticateWithPhoneNumber throws auth/user-mismatch error

### ISSUE THREAD

**Issue by jakehockey10** [angular/angularfire#3495]
### Version info

``` shell
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.9
Node: 18.17.1
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cdk                    17.0.4
@angular/cli                    17.0.9
@angular/fire                   17.0.0
@angular/material               17.0.4
@schematics/angular             17.0.9
ng-packagr                      17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
    
```

**Angular:** 17.0.9 (CLI)

**Firebase:** CLI? 13.0.2

**AngularFire:**: 17.0.0

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

**Steps to set up and reproduce**

- Enable MFA on the firebase project.
- Add second factor to logged in user
- attempt to re-authenticate the user on sensitive actions like, change-password as suggested [here](https://cloud.google.com/identity-platform/docs/work-with-mfa-users#re-authenticating_a_user)

``` typescript
import { inject } from '@angular/core';
import { Auth, user } from '@angular/fire/auth';

@Injectable({providedIn: 'root'})
export class AuthService {
  readonly #auth = inject(Auth);

  readonly user$ = user(this.#auth);

  reauthenticateWithPhone(phoneNumber: string) {
    const verifier = new RecaptchaVerifier(
      this.#auth,
      'recaptcha-container-id',
      {
        size: 'invisible',
        callback: (response: unknown) =>
          console.log('RecaptchaVerifier callback: ', response),
        'expired-callback': (response: unknown) =>
          console.log('RecaptchaVerifier expired-callback: ', response),
        'error-callback': (response: unknown) =>
          console.log('RecaptchaVerifier error-callback: ', response),
      }
    );
    verifier.render();

    return this.user$.pipe(
      filter(Boolean),
      switchMap((user) =>
        from(reauthenticateWithPhoneNumber(user, phoneNumber, verifier))
      ),
      switchMap((confirmationResult) => {
        const verificationCode = prompt('Enter verification code');
        if (!verificationCode) throw Error('Verification code is missing');
        return from(confirmationResult.confirm(verificationCode));
      })
    );
  }
}

```

``` typescript
const enrolledFactors = multiFactor(this.#auth.currentUser).enrolledFactors;
const phoneFactor = enrolledFactors.find((factor) => factor.factorId === 'phone');

// I have to cast to any here, because the `MultiFactorInfo` type doesn't include `phoneNumber`, but its there if you spit out the object in the console or template with `JsonPipe`
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const phoneNumber = (phoneFactor as any).phoneNumber;
```

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **

``` console
auth.service.ts:83 FirebaseError: Firebase: Error (auth/user-mismatch).
    at createErrorInternal (index-dd468b12.js:500:41)
    at _assert (index-dd468b12.js:506:15)
    at index-dd468b12.js:5357:9
    at Generator.next (<anonymous>)
    at fulfilled (chunk-ENBES6XL.js?v=8a7b3a5a:39:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:14723:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at _Zone.run (zone.js:129:43)
    at zone.js:1257:36
```

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

** Firebase Emulators logging: **
``` shell
i  To verify the email address <my-email>, follow this link: http://127.0.0.1:9099/emulator/action?mode=verifyEmail&lang=en&oobCode=yc3gC2zE9y_kaD1uO31mCbhSzAnsbQkwiYhVSH-wZNmvkrbimKo2R6&apiKey=fake-api-key
i  functions: Beginning execution of "us-central1-createUserDocument"
i  functions: Finished "us-central1-createUserDocument" in 797.953373ms
i  To enroll MFA with +13033033003, use the code 757925.
i  To verify the phone number +13033033003, use the code 078298.
i  functions: Beginning execution of "us-central1-createUserDocument"
i  functions: Finished "us-central1-createUserDocument" in 32.501548ms
```

### Expected behavior

I'm using the correct phone number because I'm getting it from the enrolledFactor object itself.  I would expect that reauthenticating with the enrolled factor I have successfully setup with this phone number I'm using would not throw a `auth/user-mismatch` error.

### Actual behavior

Instead, I get a `auth/user-mismatch` error.  [According to the documentation](https://firebase.google.com/docs/reference/js/v8/firebase.User#error-codes_8), this is an indication that the credential being used is not associated with the user I provided.  But the credential is being provided to me and the user object is being provided to me.

I've also wondered if this was because I was also unable to successfully update the current user's phoneNumber with the `updatePhoneNumber` function.  I've tried, unsuccessfully, to call this function with the credential I used when enrolling the factor and creating a new credential, which requiring another verification code and still didn't work.  That's when I learned that the reason for this is this error here: `"UNSUPPORTED_FIRST_FACTOR : A phone number cannot be set as a first factor on an SMS based MFA user."`.  I'm not sure what else to try here and was hoping for some help :)

I'm attempting to have SMS auth run before the user is allowed to follow through with changing their password.  Before I call `updatePassword` from `@angular/fire/auth`, I call `reauthenticateWithCredential`:

``` typescript
from(
  reauthenticateWithCredential(
    user,
    EmailAuthProvider.credential(user.email, currentPassword)
  )
).pipe(
  switchMap((credential) =>
    from(updatePassword(credential.user, newPassword))
  )
);
```

Is this because I'm supposed to call the `reauthenticateWith[...]` method that matches my primary authentication type?  Is it possible to request SMS auth while the user is already logged in via email/password using firebase for angular?

**Comment by jakehockey10** [comment]
I believe I've made a mistake reporting this as a bug.  I have realized that once sms mfa is enabled for an email/password-based user, reauthenticating with email/password-based credential will require the user to perform phone number verification without me having to invoke it explicitly.  I just need to handle the `MultiFactorError` as I do with login and it works like a charm.
