### ISSUE TITLE
[error] AssertionError [ERR_ASSERTION]: catch clause variable is not an Error instance

### ISSUE THREAD

**Issue by shampau** [angular/angularfire#3504]
sorry if i am asking this here but i cant get this done in any way as i have limited knowledge in this part.
so what happens is i cant set up the authentication, firestore, and cloud storage in my project, it keeps showing this error,

`[error] AssertionError [ERR_ASSERTION]: catch clause variable is not an Error instance`

```
at assertIsError (C:\Users\PATH\node_modules\@angular\cli\src\utilities\error.js:19:26)
at AddCommandModule.runSchematic (C:\Users\PATH\node_modules\@angular\cli\src\command-builder\schematics-command-module.js:266:43)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AddCommandModule.executeSchematic (C:\Users\PATH\node_modules\@angular\cli\src\commands\add\cli.js:279:20)
at async AddCommandModule.handler (C:\Users\PATH\node_modules\@angular\cli\src\command-builder\command-module.js:119:24)
```

This is whats in assert error
```
function assertIsError(value) {
    const isError = value instanceof Error ||
        // The following is needing to identify errors coming from RxJs.
        (typeof value === 'object' && value && 'name' in value && 'message' in value);
    (0, assert_1.default)(isError, 'catch clause variable is not an Error instance');
}
```

i dont know whats causing this but i have all my packages up to date

**Comment by shampau** [comment]
Solved at last
tried this
`npm install firebase-tools`
and tried setting up the fire features again and it worked
