### ISSUE TITLE
Unhandled Promise rejection Analytics with SSR 

### ISSUE THREAD

**Issue by Karman40** [angular/angularfire#3511]
## APP VERSION
```
Angular CLI: 16.2.10
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@angular/fire                   16.0.0
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      5.0.4
zone.js                         0.13.3
```

## ERROR MESSAGE
```
1|RSR PUBLIC  | 2024-03-30T22:40:00: Unhandled Promise rejection: Cannot set headers after they are sent to the client ; Zone: <root> ; Task: Promise.then ; Value: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at new NodeError (node:internal/errors:405:5)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at ServerResponse.setHeader (node:_http_outgoing:648:11)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.set.res.header (/home/rsr/webapps/rsr-public/server/main.js:1:540726)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.location (/home/rsr/webapps/rsr-public/server/main.js:1:541653)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.redirect (/home/rsr/webapps/rsr-public/server/main.js:1:541954)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at /home/rsr/webapps/rsr-public/server/main.js:1:3806732
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at _ZoneDelegate.invoke (/home/rsr/webapps/rsr-public/server/main.js:1:1666887)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at Zone3.run (/home/rsr/webapps/rsr-public/server/main.js:1:1659708)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at /home/rsr/webapps/rsr-public/server/main.js:1:1683481
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at _ZoneDelegate.invokeTask (/home/rsr/webapps/rsr-public/server/main.js:1:1667729) {
1|RSR PUBLIC  | 2024-03-30T22:40:00:   code: 'ERR_HTTP_HEADERS_SENT'
1|RSR PUBLIC  | 2024-03-30T22:40:00: } Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at new NodeError (node:internal/errors:405:5)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at ServerResponse.setHeader (node:_http_outgoing:648:11)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.set.res.header (/home/rsr/webapps/rsr-public/server/main.js:1:540726)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.location (/home/rsr/webapps/rsr-public/server/main.js:1:541653)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at res.redirect (/home/rsr/webapps/rsr-public/server/main.js:1:541954)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at /home/rsr/webapps/rsr-public/server/main.js:1:3806732
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at _ZoneDelegate.invoke (/home/rsr/webapps/rsr-public/server/main.js:1:1666887)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at Zone3.run (/home/rsr/webapps/rsr-public/server/main.js:1:1659708)
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at /home/rsr/webapps/rsr-public/server/main.js:1:1683481
1|RSR PUBLIC  | 2024-03-30T22:40:00:     at _ZoneDelegate.invokeTask (/home/rsr/webapps/rsr-public/server/main.js:1:1667729)
```

## app.module.ts
```
import {initializeApp, provideFirebaseApp} from "@angular/fire/app";
import {getAnalytics, provideAnalytics, ScreenTrackingService, UserTrackingService} from "@angular/fire/analytics";
import {getPerformance, providePerformance} from "@angular/fire/performance";

... 

provideFirebaseApp(() => initializeApp(environment.firebase)),
provideAnalytics(() => getAnalytics()),
providePerformance(() => getPerformance()),

...

providers: [ScreenTrackingService, UserTrackingService],
```

**Comment by armando-navarro** [comment]
The stack trace here is an Express `ERR_HTTP_HEADERS_SENT` from `res.redirect` calling `res.setHeader` after the response was already sent, which is application and server code rather than AngularFire. It also targets the deprecated `@nguniversal` express-engine with Angular 16 and `@angular/fire` 16.

I am closing this since there is no AngularFire defect evident and no minimal reproduction. If you can reproduce an Analytics-specific SSR failure on a current `@angular/fire` with the modern `@angular/ssr`, please open a new issue with a minimal reproduction.
