### ISSUE TITLE
Timeout just in the first load with Angular 18 and SSR

### ISSUE THREAD

**Issue by quedicesebas** [angular/angularfire#3551]
### Version info

**Angular:** 18.0.3

**Firebase:** 

**AngularFire:** 

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**

Clone this repository: https://github.com/quedicesebas/lacomanda-front

**Sample data and security rules**

I'm just loading the SEO meta tags info form firebase.

You just need to use this two documents:

brandDomains/[lafocachera.co](http://lafocachera.co/)
{"brandId": "lafocachera"}

seoConfigs/lafocachera
{
  "meta":
     "card": "summary",
     "description": "FOCACCIA Y PIZZA AL TAGLIO. Para llevar o DIRECTO A TU CASA",
     "image": "https://lafocachera.co/assets/lafocachera/meta.jpg",
     "type": "website",
      "url": "https://lafocachera.co/"
  },
   "title "La Focachera - Domicilios MOSQUERA FUNZA Y MADRID"
}

### Debug output
I got this just the first time. If I press F5, reloads well each consequent time.
```
Page / did not render in 30 seconds.
    at Timeout.<anonymous> (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\@angular\build\src\utils\server-rendering\render-page.js:90:90)
    at Timeout.timer (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:2249:37)
    at _ZoneDelegate.invokeTask (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:398:33)
    at _ZoneImpl.runTask (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:158:47)
    at invokeTask (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:479:34)
    at Timeout.ZoneTask.invoke (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:468:48)
    at Timeout.data.args.<computed> (C:\Users\srrge\source\repos\esaes\alacarta\lacomanda-front\node_modules\zone.js\fesm2015\zone-node.js:2231:32)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7
```

### Expected behavior

Should load the first-time without timeout

### Actual behavior

Timeout the first load (in local and deployed to Firebase App Hosting also)

**Comment by alexdabast** [comment]
@quedicesebas did you find anything about this ?

**Comment by sadabjr** [comment]
did you get any solution ?

**Comment by JanKrakowiak** [comment]
same, did you find something?

**Comment by juliansojjj** [comment]
Same, working with firebase. Initially implemented `provideExperimentalZonelessChangeDetection()` and later deactivated it, and the error persists.

**Comment by ibnYusrat** [comment]
All I did to end up with this error was to generate a new app and add AngularFire to it. I am starting to loose hope with the Angular Fire library, like really loose hope.. after using it for 5 years.

**Comment by quedicesebas** [comment]
Is working for me sometime ago, not sure why.

**Comment by jamesdaniels** [comment]
Please give AngularFire v19 a spin, we've improved the zone handling and now emit debug messages warning the developer of zonewraps that may be misbehaving.

**Comment by hanafnafs** [comment]
Same issue here, have you found any solution?

**Comment by BIYUEHU** [comment]
Same, have u solved it?
