### ISSUE TITLE
Update to firebase-js-sdk 11.0.0 fails: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app)

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angularfire#3573]
Hi, when upgrading from firebase-js-sdk 10.x to firebase-js-sdk 11.0.0 we get the following error.
Even though as you can see, we did call initializeApp() first.

![Image](https://github.com/user-attachments/assets/7bcec6f8-6b78-49b4-b5e8-716f05e1a321)
![Image](https://github.com/user-attachments/assets/79788e4f-1fd9-477c-9acc-e283eaa3361d)
![Image](https://github.com/user-attachments/assets/ea326cae-f060-44e1-879f-ce8af40090a6)
![Image](https://github.com/user-attachments/assets/71cf2e43-0a9f-4d7a-9647-c5afc0cf61f7)
![Image](https://github.com/user-attachments/assets/5e11ab7d-88c1-4f93-af7e-f57f93d028fa)

**Comment by JGSolutions** [comment]
Is there any support for this project?

**Comment by jamesdaniels** [comment]
@JGSolutions "support" is a loaded term, we are not a supported product as it related to the Google Cloud terms of service—but there are people working on the library.

AngularFire v18 is not compatible with Firebase v11, we need better error messaging in the JS SDK but the odd error messages that you are seeing here is because your environment has multiple conflicting versions of Firebase installed.

AngularFire v19 will support Firebase v11 and Angular v19, we just released v19.0.0-rc.2. `ng add @angular/fire@next` if this RC is looking good I'll plan to cut v19 final shortly.

**Comment by JGSolutions** [comment]
Ok thanks for the help.

Maybe support was the wrong word to use. 

i was able to comile and start the server when i run the app i get this:

app.routes.ts:49 ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
    at injectInjectorOnly (core.mjs:1095:11)
    at ɵɵinject (core.mjs:1105:40)
    at inject (core.mjs:1190:10)
    at run (angular-fire.mjs:115:10)
    at angular-fire.mjs:162:56
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6494:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40

i think this something on my side which I am looking into

**Comment by jamesdaniels** [comment]
@JGSolutions no worries.

Yeah, that's the error that caused us a lot of grief in our test suite. It turns out that the rxjs-interopt pipe we're using in our methods to make them SSR safe requires an injection context. So you can used it outside of a component or provider factory. If it's in a test you can't used wrap in TestBed.provideInjectionContext

Because that was a forcing function we're now reshuffling a lot of our stuff to use inject() internally rather than rely on constructor injection. Sorry that seems to be making for a rougher upgrade 😞

**Comment by JGSolutions** [comment]
@jamesdaniels As long you guys are aware of the problem and you guys are on it, all good with me.

Thanks again

**Comment by jamesdaniels** [comment]
@JGSolutions our zone wrappers will now noop when outside of an injector context, cutting `rc.3` now, give that a spin and LMK how it goes

**Comment by JGSolutions** [comment]
@jamesdaniels 
Thanks for the quick update.

Still happening but seems at a different line number: at run (angular-fire.mjs:115:10)

chunk-DZ7BV6I4.js?v=05488ea1:59 ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
    at injectInjectorOnly (core.mjs:1095:11)
    at ɵɵinject (core.mjs:1105:40)
    at inject (core.mjs:1190:10)
    at run (angular-fire.mjs:115:10)
    at angular-fire.mjs:170:48
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6494:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40

**Comment by jamesdaniels** [comment]
yeah I caught that one earlier today, addressing in #3590

**Comment by jamesdaniels** [comment]
Rc.4 out.

**Comment by JGSolutions** [comment]
@jamesdaniels Amazing it works!

**Comment by JGSolutions** [comment]
can i push this to prod or should i wait?

@jamesdaniels

**Comment by alexfung888** [comment]
with rc.4, the application no longer fails, but every invocation of some imported function results in a warning in the console.log. Is it an expected behavior for the time being? 

Functions that issue warnings include:
```ts
authState() // import from '@angular/fire/auth'
objectVal()/listVal() // (import from '@angular/fire/database' or 'rxfire/database') 
ref() // (import from '@angular/fire/database') 

```

The warning reads:
```
Firebase API called outside injection context: ɵzoneWrap(<name of function>)
```

**Comment by jamesdaniels** [comment]
Yes, those warnings are safe to ignore and are just breadcrumbs incase you run into any zone / rehydration instabilities. We have docs for that inbound.
