### ISSUE TITLE
Pagination with startAfter : Hn is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by alhendi99** [angular/angularfire#3599]
I am working on an Angular application using the following versions: 
@angular/fire: 7.5.0 
@angular/core: 15.2.0
firebase: 9.17.1 Node.js: v20.11.1

I am implementing pagination for a Firestore query using startAfter with lastVisible, which is expected to be a DocumentSnapshot. While the logic works in most cases, i get this error:

```sh
TypeError: Hn is not a function or its return value is not iterable
    at index.esm2017.js:19940:33
    at Ul (index.esm2017.js:19951:5)
    at $l._apply (index.esm2017.js:19876:19)
    at Rl (index.esm2017.js:19608:30)
    at angular-fire.js:227:48
    at angular-fire.js:160:59
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.run (zone.js:134:43)
    at NgZone.runOutsideAngular (core.mjs:24159:28)
    at runOutsideAngular (angular-fire.js:160:35)
Here is the code I used for pagination:
```

```ts
queryRef = query(
    collection(this.firestore.firestore, "Inventory_Transfers"),
    where("is_deleted", "==", false),
    where("restaurant_id", "==", restaurantId),
    where("status_by_portal_tab", "==", statusByPortalTab),
    where("requester_type", "==", requesterType),
    where("branch_ids_requested_for", "array-contains-any", batch),
    orderBy("create_on", "desc"),
    startAfter(lastVisible),
    limit(batchSize)
);
```

**Comment by armando-navarro** [comment]
Thanks for the report. This is on @angular/fire 7.5.0 / firebase 9.17.1 / Angular 15, which are several major versions out of support, and the minified 'Hn is not a function' from startAfter usually points to a version or bundling mismatch on that old compat-era stack. Those APIs have been replaced by the modular API.

If you still hit this with the modular API on a current version, please reopen with a minimal repro and we will take a look.
